language: java
jdk:
  - oraclejdk7
before_install:
  - chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: q1XL7eTKPqsV1G0duN+yFZ489OXQ5MBfjD2uaY0INymnPhCroUsEYOu3vlzllpTbXqotTEFdfUqP7H7SKlzEoSfwBc1qfWzlNIrpvd/U9b6RLUUbNiWw3oU8JeUWtXllij/qlZ/FCGLR0FKFdhfcS8GyjkHsP0YKK0sEQcnNyzTN5tZuX/gQIbhnIZPzd3p0Za0l2DlUMOyUBzWa8ECD7e10U86wtpbalwoiMOPEOclHu7IFW4Zwcgv+xTkmFmUyYkBMd+Ji/a0YvrEUtoTs+OOy9tI0gZnvJuPnf3wslmO9JvoLhYdPmdifjAggPfSbezfzpVFGmdGw82frwv/B6TcmdQ9T5ovzUw/qJJV+fXO2Zturh6Yl7dOmIScX2gtnHlElK966soIkajU/Gh7YHOidORxpCt09ryp98sAdemD3QZkvkyP9Nf/ZNdOYKVdoquP0YMnUcErHlt1NAynrsIraN0uvxbvzGYMpCa6mn1aoiW2xV7OoegA86xRFaQTW9PFGBnh2JbSMq7ok8FomaDCz+lFyNgrH0ZkN6IRwQ1GjNtskKASCx5uD8sBFQifQfCBB3XRvOZezgRa/1cr3ipL+6SRaIEuKPD1aGkmdiTV3kz/AibSNUCZRhn1wAI/Y1HWZQz8fHcC+p3FRDqo6/g9FNx2QaPAlUFmkDV3jfHY=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/build/libs/EnhancedCore_*.jar
  skip_cleanup: true
  on:
    tags: true
